[phases.setup]
aptPkgs = ["libreoffice", "libreoffice-writer", "libreoffice-calc", "libreoffice-impress"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run postinstall"]

[start]
cmd = "npm start"